### ISSUE TITLE
Fatal error when PHPUnit throws notices since PIEP v2

### ISSUE THREAD

**Issue by Bilge** [ScriptFUSION/PHPUnit-Immediate-Printer#8]
>PHP Fatal error:  Uncaught Error: Call to undefined method PHPUnit_Framework_Error_Notice::getPreviousWrapped() in /scriptfusion/phpunit-immediate-exception-printer/src/Printer.php:159
Stack trace:
#0 /scriptfusion/phpunit-immediate-exception-printer/src/Printer.php(103): ScriptFUSION\PHPUnitImmediateExceptionPrinter\PhpUnit5Printer->writeException(Object(PHPUnit_Framework_Error_Notice))
#1 /scriptfusion/phpunit-immediate-exception-printer/src/PhpUnit5Printer.php(26): ScriptFUSION\PHPUnitImmediateExceptionPrinter\PhpUnit5Printer->onEndTest(Object(), 0.99986386299133)
#2 /phpunit/phpunit/src/Framework/TestResult.php(399): ScriptFUSION\PHPUnitImmediateExceptionPrinter\PhpUnit5Printer->endTest(Object(), 0.99986386299133)
#3 /phpunit/phpunit/src/Framework/TestResult.php(889): PHPUnit_Framework_TestResult->endTest(Object( in /scriptfusion/phpunit-immediate-exception-printer/src/Printer.php on line 159

**Comment by Bilge** [comment]
v2 should be considered yanked.
